import BackToTop from "@/components/elements/BackToTop";
import DataBg from "@/components/elements/DataBg";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import PageHead from "@/components/layout/PageHead";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@/assets/css/bootstrap.min.css";
import "@/assets/css/animate.min.css";
import "@/assets/css/magnific-popup.css";
import "@/assets/css/fontawesome-all.min.css";
import "@/assets/css/odometer.css";
import "@/assets/css/tg-cursor.css";
import "@/assets/css/default.css";
import "@/assets/css/jarallax.css";
import "@/assets/css/style.css";
import "@/assets/css/responsive.css";

export const metadata = {
  title: "RD Construction - Expert Renovation Services in New Jersey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <PageHead
          headTitle={
            "RD Construction - Expert Renovation Services in New Jersey"
          }
        /> */}
        <DataBg />
        <Header headerCls="transparent-header" headerTop={false} />
        {children}
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
